import type { Beer, Brewery, Gear, Glass } from "./types";

// Product data lifted from Catálogo CCO 2026 (prices MXN, IVA+IEPS incl.)
export const BREWERIES: Brewery[] = [
  {
    id: "cardera",
    name: "Cerveza Cardera",
    origin: "Ensenada, B.C.",
    logo: "/assets/logo-cardera-dark.png",
    logoLight: "/assets/logo-cardera-light.png",
    moq: 24,
  },
  {
    id: "308",
    name: "Cervecería 308",
    origin: "Navojoa, Sonora",
    logo: "/assets/logo-cco.png",
    logoLight: "/assets/logo-cco.png",
    moq: 24,
  },
];

export const BREWERY_COORDS: Record<string, string> = {
  cardera: "31.86°N 116.60°W",
  "308": "27.07°N 109.44°W",
};

export const BEERS: Beer[] = [
  {
    id: "slender",
    brewery: "cardera",
    name: "Slender",
    style: "Light Lager",
    abv: 3.5,
    ibu: 8.4,
    tag: "linea",
    award: "Plata",
    img: "/assets/beer-slender.png",
    desc: {
      es: "Pálida, brillante y cristalina. Aromas de malta con un toque de frutas blancas; cuerpo ligero y alta efervescencia.",
      en: "Pale, bright and crystal clear. Malt aroma with a hint of white fruit; light body, highly effervescent.",
    },
    formats: [{ id: "keg20", label: "Barril PET 20L", price: 2349, unit: 1 }],
  },
  {
    id: "vienna",
    brewery: "cardera",
    name: "Vienna Lager",
    style: "Vienna Lager",
    abv: 5.5,
    ibu: 23.9,
    tag: "temporada",
    img: "/assets/beer-vienna.png",
    desc: {
      es: "Ámbar claro, espuma blanca, notas de corteza de pan y un toque acaramelado al final.",
      en: "Light amber, white head, bread-crust notes with a caramel finish. Light and refreshing.",
    },
    formats: [{ id: "keg20", label: "Barril PET 20L", price: 2349, unit: 1 }],
  },
  {
    id: "berrinchuda",
    brewery: "cardera",
    name: "Berrinchuda",
    style: "Blonde de Frambuesa",
    abv: 4.5,
    ibu: 14,
    tag: "linea",
    award: "Bronce 2025",
    img: "/assets/beer-berrinchuda.png",
    desc: {
      es: "Rojo intenso, espuma rosada. Aroma a frambuesa con ligera acidez por la fruta natural.",
      en: "Deep red with a pink head. Raspberry-forward aroma, gentle acidity from real fruit.",
    },
    formats: [
      { id: "can12", label: "Lata sleek 12oz ×12", price: 814.32, unit: 12 },
      { id: "keg20", label: "Barril PET 20L", price: 2581, unit: 1 },
    ],
  },
  {
    id: "rosice",
    brewery: "cardera",
    name: "Rosice",
    style: "Session IPA c/ Vino Rosado",
    abv: 8,
    ibu: 30,
    tag: "limitada",
    img: "/assets/beer-berrinchuda.png",
    desc: {
      es: "Mezcla 50/50 de session IPA con vino rosado Nebbiolo–Carignan 2024 del Valle de Guadalupe.",
      en: "50/50 blend of our session IPA with a 2024 Nebbiolo–Carignan rosé from Valle de Guadalupe.",
    },
    formats: [
      { id: "can12", label: "Lata sleek 12oz ×12", price: 1252.8, unit: 12 },
    ],
  },
  {
    id: "bohemian",
    brewery: "cardera",
    name: "Bohemian Pils",
    style: "Czech Lager",
    abv: 4.2,
    ibu: 30,
    tag: "temporada",
    img: "/assets/beer-bohemian.png",
    desc: {
      es: "Dorado profundo, espuma compacta. Balance perfecto entre malta y lúpulos nobles.",
      en: "Deep gold, compact head. Perfect balance of malt and noble hops with decoction character.",
    },
    formats: [
      { id: "can12", label: "Lata sleek 12oz ×12", price: 765.6, unit: 12 },
      { id: "keg20", label: "Barril PET 20L", price: 2813, unit: 1 },
    ],
  },
  {
    id: "murky",
    brewery: "cardera",
    name: "Murky Mosice",
    style: "Hazy Pale Ale",
    abv: 4.9,
    ibu: 30,
    tag: "linea",
    award: "Bronce 2024",
    img: "/assets/beer-murky-mosice.png",
    desc: {
      es: "Turbia, dorado pajizo. Mango, piña y cítricos de los lúpulos Mosaic, Simcoe y Centennial.",
      en: "Hazy straw gold. Ripe mango, pineapple and citrus from Mosaic, Simcoe and Centennial hops.",
    },
    formats: [{ id: "keg20", label: "Barril PET 20L", price: 3161, unit: 1 }],
  },
  {
    id: "xpa",
    brewery: "cardera",
    name: "Extra Pale Ale 2026",
    style: "Pale Ale",
    abv: 5.2,
    ibu: 40,
    tag: "linea",
    img: "/assets/beer-mosice.png",
    desc: {
      es: "Dorado nítido. Cáscara de naranja y limón con nota herbácea y un toque de miel al final.",
      en: "Crisp gold. Orange and lemon peel with an herbal note and a touch of honey at the finish.",
    },
    formats: [{ id: "keg20", label: "Barril PET 20L", price: 2929, unit: 1 }],
  },
  {
    id: "mosice",
    brewery: "cardera",
    name: "Mosice",
    style: "Session IPA",
    abv: 4.8,
    ibu: 40,
    tag: "linea",
    img: "/assets/beer-mosice.png",
    desc: {
      es: "Alto impacto lupulado: mango y piña con cítricos. Ligera, seca y refrescante.",
      en: "High hop impact: mango and pineapple with citrus. Light, dry and refreshing.",
    },
    formats: [
      { id: "can16", label: "Lata 16oz ×12", price: 1016.16, unit: 12 },
      { id: "keg20", label: "Barril PET 20L", price: 2929, unit: 1 },
    ],
  },
  {
    id: "73millas",
    brewery: "cardera",
    name: "73 Millas to Hoppyness",
    style: "Doble IPA",
    abv: 8.5,
    ibu: 55,
    tag: "linea",
    award: "Plata Colombia 2023",
    img: "/assets/beer-73-millas.png",
    desc: {
      es: "Dorado cobrizo. Ataque lupulado cítrico y herbal con final cálido.",
      en: "Copper gold. Citrus-herbal hop attack with a warming finish.",
    },
    formats: [
      { id: "can12", label: "Lata sleek 12oz ×12", price: 974.4, unit: 12 },
      { id: "keg20", label: "Barril PET 20L", price: 3509, unit: 1 },
    ],
  },
  {
    id: "haze",
    brewery: "cardera",
    name: "Straight to Haze",
    style: "Hazy IPA",
    abv: 5.5,
    ibu: 36,
    tag: "linea",
    award: "Oro 2023 · Mejor IPA",
    img: "/assets/beer-murky-mosice.png",
    desc: {
      es: "Jugosa y de gran cuerpo. Frutas tropicales, cítricos y coco de Bru-1, Mosaic, El Dorado y Sabro.",
      en: "Juicy, full-bodied. Tropical fruit, citrus and coconut from Bru-1, Mosaic, El Dorado and Sabro.",
    },
    formats: [{ id: "can16", label: "Lata 16oz ×12", price: 1016.16, unit: 12 }],
  },
  {
    id: "gardenia",
    brewery: "cardera",
    name: "Buena Vida Gardenia",
    style: "West Coast IPA",
    abv: 7,
    ibu: 60,
    tag: "limitada",
    img: "/assets/beer-73-millas.png",
    desc: {
      es: "DDH West Coast IPA con Cryo Krush, Cryo Mosaic, Cashmere y El Dorado. Colaboración Gardenia.",
      en: "DDH West Coast IPA with Cryo Krush, Cryo Mosaic, Cashmere and El Dorado. Gardenia collab.",
    },
    formats: [{ id: "can16", label: "Lata 16oz ×12", price: 1044, unit: 12 }],
  },
  {
    id: "rough",
    brewery: "cardera",
    name: "Rough 2020",
    style: "Black IPA",
    abv: 6.2,
    ibu: 50,
    tag: "temporada",
    img: "/assets/beer-rough.png",
    desc: {
      es: "Café casi negro, espuma moka. Tostado dulce con resina, pino y cítricos del lúpulo.",
      en: "Near-black brown, mocha head. Sweet roast with resin, pine and citrus hop notes.",
    },
    formats: [
      { id: "can16", label: "Lata 16oz ×12", price: 1044, unit: 12 },
      { id: "keg20", label: "Barril PET 20L", price: 2929, unit: 1 },
    ],
  },
  {
    id: "oatmeal",
    brewery: "cardera",
    name: "Oatmeal Stout",
    style: "Oatmeal Stout",
    abv: 5.8,
    ibu: 30,
    tag: "linea",
    img: "/assets/beer-oatmeal.png",
    desc: {
      es: "Chocolate y café tostado con final frutal. Cuerpo medio, respaldo de avena.",
      en: "Chocolate and roasted coffee with a fruity finish. Medium body, oat backbone.",
    },
    formats: [
      { id: "can12", label: "Lata sleek 12oz ×12", price: 814.32, unit: 12 },
      { id: "keg20", label: "Barril PET 20L", price: 2511.4, unit: 1 },
    ],
  },
  {
    id: "strong",
    brewery: "cardera",
    name: "Strong Ale",
    style: "American Strong Ale",
    abv: 7,
    ibu: 45,
    tag: "limitada",
    img: "/assets/beer-vienna.png",
    desc: {
      es: "Ámbar profundo. Impacto maltoso con lúpulos resinosos y terrosos.",
      en: "Deep amber. Malt-driven with resinous, earthy hop notes.",
    },
    formats: [{ id: "keg20", label: "Barril PET 20L", price: 2465, unit: 1 }],
  },
  {
    id: "jakport",
    brewery: "cardera",
    name: "Jak Port",
    style: "Porter Bourbon BA",
    abv: 6,
    ibu: 28,
    tag: "limitada",
    img: "/assets/beer-jak-port.png",
    desc: {
      es: "Porter madurada 12 meses en barrica de bourbon. Vainilla, caramelo, chocolate negro y pasas.",
      en: "Porter aged 12 months in bourbon barrels. Vanilla, caramel, dark chocolate and raisin.",
    },
    formats: [{ id: "keg20", label: "Barril PET 20L", price: 3045, unit: 1 }],
  },
  // Cervecería 308 (no label art in catalog → placeholder slots)
  {
    id: "308-ultra",
    brewery: "308",
    name: "Ultra",
    style: "Light Lager",
    abv: 4.2,
    ibu: 20,
    tag: "linea",
    img: null,
    desc: {
      es: "American Light Lager, ligera y refrescante, amarillo pajizo y espuma blanca.",
      en: "American light lager, light and refreshing, straw yellow with a white head.",
    },
    formats: [
      { id: "can355", label: "Lata 355ml", price: 39, unit: 1 },
      { id: "keg20", label: "Barril PET 20L", price: 1850, unit: 1 },
    ],
  },
  {
    id: "308-pale",
    brewery: "308",
    name: "Pale Ale",
    style: "Pale Ale",
    abv: 4.7,
    ibu: 22,
    tag: "linea",
    img: null,
    desc: {
      es: "Dorada y refrescante, balance entre malta y lúpulo con aromas cítricos y sabor tropical.",
      en: "Golden and refreshing, malt–hop balance with citrus aroma and tropical flavor.",
    },
    formats: [
      { id: "can355", label: "Lata 355ml", price: 45, unit: 1 },
      { id: "keg20", label: "Barril PET 20L", price: 2192, unit: 1 },
    ],
  },
  {
    id: "308-brown",
    brewery: "308",
    name: "Brown Ale",
    style: "Brown Ale",
    abv: 4.6,
    ibu: 20,
    tag: "linea",
    img: null,
    desc: {
      es: "Estilo inglés, ámbar oscuro, suave dulzor de malta con carácter a caramelo.",
      en: "English style, dark amber, soft malt sweetness with light caramel character.",
    },
    formats: [
      { id: "can355", label: "Lata 355ml", price: 49, unit: 1 },
      { id: "keg20", label: "Barril PET 20L", price: 2295, unit: 1 },
    ],
  },
  {
    id: "308-white",
    brewery: "308",
    name: "Belgian White",
    style: "Belgian White",
    abv: 4.5,
    ibu: 22,
    tag: "linea",
    img: null,
    desc: {
      es: "Malta de trigo y cáscara de naranja: fresca, sedosa y cítrica.",
      en: "Wheat malt and orange peel: fresh, silky and citrusy.",
    },
    formats: [
      { id: "can355", label: "Lata 355ml", price: 49, unit: 1 },
      { id: "keg20", label: "Barril PET 20L", price: 2295, unit: 1 },
    ],
  },
  {
    id: "308-seltzer",
    brewery: "308",
    name: "Hard Seltzer",
    style: "Hard Seltzer",
    abv: 4.0,
    ibu: 0,
    tag: "linea",
    img: null,
    desc: {
      es: "Bebida fermentada con toque de limón. Refrescante, baja en calorías y sin gluten.",
      en: "Fermented seltzer with a hint of lime. Refreshing, low-cal and gluten-free.",
    },
    formats: [
      { id: "can355", label: "Lata 355ml", price: 59, unit: 1 },
      { id: "keg20", label: "Barril PET 20L", price: 2550, unit: 1 },
    ],
  },
  {
    id: "308-kolsch",
    brewery: "308",
    name: "Kölsch",
    style: "Kölsch",
    abv: 4.7,
    ibu: 25,
    tag: "linea",
    img: null,
    desc: {
      es: "Estilo alemán, dorada, ligera y refrescante. Buena opción para comenzar.",
      en: "German style, golden, light and refreshing. A great starting point.",
    },
    formats: [
      { id: "can355", label: "Lata 355ml", price: 49, unit: 1 },
      { id: "keg20", label: "Barril PET 20L", price: 2295, unit: 1 },
    ],
  },
  {
    id: "308-sour",
    brewery: "308",
    name: "Sour Ale",
    style: "Sour Ale",
    abv: 5.2,
    ibu: 2,
    tag: "temporada",
    img: null,
    desc: {
      es: "Sour con frutos rojos. Ácida y refrescante, algo diferente.",
      en: "Red-fruit sour. Tart and refreshing, something different.",
    },
    formats: [
      { id: "can355", label: "Lata 355ml", price: 55, unit: 1 },
      { id: "keg20", label: "Barril PET 20L", price: 2481, unit: 1 },
    ],
  },
  {
    id: "308-ipa",
    brewery: "308",
    name: "IPA West Coast",
    style: "West Coast IPA",
    abv: 6.2,
    ibu: 66,
    tag: "linea",
    img: null,
    desc: {
      es: "Cargada de lúpulo: amargor, resina y cítricos fieles al estilo.",
      en: "Hop-loaded: bitterness, resin and citrus true to style.",
    },
    formats: [
      { id: "can355", label: "Lata 355ml", price: 59, unit: 1 },
      { id: "keg20", label: "Barril PET 20L", price: 2550, unit: 1 },
    ],
  },
  {
    id: "308-stout",
    brewery: "308",
    name: "Oatmeal Stout",
    style: "Oatmeal Stout",
    abv: 3.9,
    ibu: 40,
    tag: "linea",
    img: null,
    desc: {
      es: "Inglesa oscura con chocolate y café tostado. Suave al paladar. Disponible en Nitro.",
      en: "Dark English stout with dark chocolate and roasted coffee. Smooth. Nitro available.",
    },
    formats: [
      { id: "can355", label: "Lata 355ml", price: 49, unit: 1 },
      { id: "keg20", label: "Barril PET 20L", price: 2295, unit: 1 },
    ],
  },
];

// Glassware: price per box, "sin tinta" / "1 tinta" (custom print)
export const GLASS: Glass[] = [
  { id: "g-pinta420", name: "Pinta 420", ml: 420, box: 12, plain: 420, inked: 540, img: "/assets/glass-pinta-420.png" },
  { id: "g-pinta490", name: "Pinta 490", ml: 490, box: 12, plain: 360, inked: 480, img: "/assets/glass-pinta-490.png" },
  { id: "g-pilsner", name: "Vaso Pilsner", ml: 320, box: 12, plain: 450, inked: 595, img: "/assets/glass-pilsner.png" },
  { id: "g-can", name: "Vaso Can Beer", ml: 473, box: 12, plain: 580, inked: 700, img: "/assets/glass-can-beer.png" },
  { id: "g-ipa", name: "Vaso IPA", ml: 615, box: 12, plain: 935, inked: 1080, img: "/assets/glass-ipa.png" },
  { id: "g-sienna", name: "Vaso Sienna", ml: 650, box: 12, plain: 840, inked: 960, img: "/assets/glass-sienna.png" },
  { id: "g-nonic", name: "Vaso Nonic", ml: 473, box: 12, plain: 580, inked: 700, img: "/assets/glass-nonic.png" },
  { id: "g-cata", name: "Vaso Cata", ml: 400, box: 12, plain: 580, inked: 700, img: "/assets/glass-cata.png" },
  { id: "g-berlin", name: "Vaso Berlín", ml: 540, box: 24, plain: 1630, inked: 1750, img: "/assets/glass-berlin.png" },
  { id: "g-taster", name: "Vaso Taster", ml: 140, box: 24, plain: 792, inked: 1032, img: "/assets/glass-taster.png" },
  { id: "g-copataster", name: "Copa Taster", ml: 160, box: 24, plain: 1400, inked: 1635, img: "/assets/glass-copa-taster.png" },
  { id: "g-teku", name: "Teku 3.0", ml: 420, box: 6, plain: 930, inked: 1050, img: "/assets/glass-teku.png" },
  { id: "g-globo", name: "Copa Globo", ml: 490, box: 12, plain: 900, inked: 1020, img: "/assets/glass-globo.png" },
];

export const GEAR: Gear[] = [
  {
    id: "k-kegerator2",
    name: "Kegerator 2 vías",
    sub: { es: "Torre 2 llaves, coples D, regulador y tanque CO₂", en: "2-tap tower, D couplers, regulator and CO₂ tank" },
    price: 16000,
    img: "/assets/keg-kegerator.png",
    moq: 1,
  },
  {
    id: "k-kegerator3",
    name: "Kegerator 3 vías",
    sub: { es: "Torre 3 llaves, coples D, regulador y tanque CO₂", en: "3-tap tower, D couplers, regulator and CO₂ tank" },
    price: 21500,
    img: "/assets/keg-kegerator.png",
    moq: 1,
  },
  {
    id: "k-co2",
    name: "Tanque de CO₂",
    sub: { es: "Carga de gas $550", en: "Gas refill $550" },
    price: 2800,
    img: "/assets/keg-regulator.png",
    moq: 1,
  },
  {
    id: "k-reg1",
    name: "Regulador 1 vía",
    sub: { es: "Regulador de presión", en: "Pressure regulator" },
    price: 1600,
    img: "/assets/keg-regulator.png",
    moq: 1,
  },
  {
    id: "k-cople",
    name: 'Cople "D" o "S"',
    sub: { es: "Conector para barril", en: "Keg coupler" },
    price: 1000,
    img: "/assets/keg-coupler.png",
    moq: 1,
  },
  {
    id: "k-grifo",
    name: "Grifo",
    sub: { es: "Llave dispensadora", en: "Dispensing faucet" },
    price: 800,
    img: "/assets/keg-grifo.png",
    moq: 1,
  },
  {
    id: "k-torre2",
    name: "Torre 2 llaves",
    sub: { es: "1 llave $1,800 · 3 llaves $2,300", en: "1-tap $1,800 · 3-tap $2,300" },
    price: 2000,
    img: "/assets/keg-torre.png",
    moq: 1,
  },
  {
    id: "k-barril20",
    name: 'Barril "D" Inox 20L',
    sub: { es: "Acero inoxidable", en: "Stainless steel" },
    price: 1200,
    img: "/assets/keg-barril-20.png",
    moq: 1,
  },
  {
    id: "k-barril30",
    name: 'Barril "D" Inox 30L',
    sub: { es: "Acero inoxidable", en: "Stainless steel" },
    price: 1500,
    img: "/assets/keg-barril-30.png",
    moq: 1,
  },
  {
    id: "k-pump",
    name: "Party Pump",
    sub: { es: "Bomba manual para barril", en: "Manual keg pump" },
    price: 1300,
    img: "/assets/keg-party-pump.png",
    moq: 1,
  },
  {
    id: "k-longneck",
    name: "Botella Long Neck 355ml",
    sub: { es: "Ámbar · caja 24 pzas", en: "Amber · case of 24" },
    price: 204,
    img: "/assets/bottle-long-neck.png",
    moq: 1,
  },
  {
    id: "k-industrial",
    name: "Botella Industrial 1L",
    sub: { es: "Ámbar · caja 12 pzas", en: "Amber · case of 12" },
    price: 345,
    img: "/assets/bottle-industrial.png",
    moq: 1,
  },
];

export const STYLE_GROUPS: Record<string, string[]> = {
  Lager: ["Light Lager", "Vienna Lager", "Czech Lager", "Kölsch"],
  "Pale Ale": ["Pale Ale", "Hazy Pale Ale", "Belgian White"],
  IPA: [
    "Session IPA",
    "Session IPA c/ Vino Rosado",
    "Doble IPA",
    "Hazy IPA",
    "West Coast IPA",
    "Black IPA",
  ],
  "Stout / Porter": ["Oatmeal Stout", "Porter Bourbon BA", "Brown Ale"],
  "Sour / Fruit": ["Blonde de Frambuesa", "Sour Ale", "Hard Seltzer"],
  Strong: ["American Strong Ale"],
};

export const BEST_SELLER_IDS = [
  "73millas",
  "mosice",
  "bohemian",
  "oatmeal",
  "308-ipa",
  "berrinchuda",
  "haze",
  "308-pale",
];

export const MOQ_BEER = 24;
export const MOQ_GLASS = 60;

export const MX_STATES = [
  "Ciudad de México",
  "Estado de México",
  "Baja California",
  "Jalisco",
  "Nuevo León",
  "Puebla",
  "Querétaro",
  "Sonora",
  "Yucatán",
];

export const REGIMENES = [
  ["601", "601 · General de Ley Personas Morales"],
  ["612", "612 · Personas Físicas con Actividad Empresarial"],
  ["626", "626 · RESICO"],
  ["621", "621 · Incorporación Fiscal"],
] as const;

export const CFDI_USES = [
  ["G01", "G01 · Adquisición de mercancías"],
  ["G03", "G03 · Gastos en general"],
  ["S01", "S01 · Sin efectos fiscales"],
] as const;
